// <auto-generated />
using System;
using BattleKnightExtensionAgent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleKnightExtensionAgent.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BattleKnightExtensionAgent.Data.Entities.DuelsSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CooldownMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelMin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LootFilterEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LootMax")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("OrdersToSkip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RankingOffset")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SkipAllOrders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SkipSpecificOrders")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("DuelsSettings");
                });

            modelBuilder.Entity("BattleKnightExtensionAgent.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BattleKnightExtensionAgent.Data.Entities.DuelsSettings", b =>
                {
                    b.HasOne("BattleKnightExtensionAgent.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("BattleKnightExtensionAgent.Data.Entities.DuelsSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
